version: 1.2
workflows:
- name: HidiveSample
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveSample.wdl
- name: HidiveCohort
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveCohort.wdl
- name: AlignPacbioBam
  subclass: wdl
  primaryDescriptorPath: /wdl/AlignPacbioBam.wdl
