version: 1.2
workflows:
- name: HidiveSample
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveSample.wdl
- name: HidiveCohort
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveCohort.wdl
- name: HidiveCluster
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveCluster.wdl
- name: HidiveRepeats
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveRepeats.wdl
- name: HidiveTrain
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveTrain.wdl
- name: HidiveSummarize
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveSummarize.wdl
- name: HidiveMSA
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveMSA.wdl
- name: HidiveSummarizeMSA
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveSummarizeMSA.wdl
- name: AlignPacbioBam
  subclass: wdl
  primaryDescriptorPath: /wdl/AlignPacbioBam.wdl
- name: SubsetAndAlignBam
  subclass: wdl
  primaryDescriptorPath: /wdl/SubsetAndAlignBam.wdl
- name: HidiveRescue
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveRescue.wdl
- name: RescueAndLocityper
  subclass: wdl
  primaryDescriptorPath: /wdl/RescueAndLocityper.wdl
- name: ValidateInPanelSamples
  subclass: wdl
  primaryDescriptorPath: /wdl/ValidateInPanelSamples.wdl
