version: 1.2
workflows:
- name: HidiveSample
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveSample.wdl
- name: HidiveCohort
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveCohort.wdl
- name: HidiveCluster
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveCluster.wdl
- name: HidiveRepeats
  subclass: wdl
  primaryDescriptorPath: /wdl/HidiveRepeats.wdl
- name: AlignPacbioBam
  subclass: wdl
  primaryDescriptorPath: /wdl/AlignPacbioBam.wdl
- name: SubsetAndAlignBam
  subclass: wdl
  primaryDescriptorPath: /wdl/SubsetAndAlignBam.wdl
