[package]
name = "hidive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow2 = "*"
bio = "*"
clap = { version = "*", features = ["derive"] }
debruijn = { git = "https://github.com/10XGenomics/rust-debruijn.git" }
noodles = "*"
parquet2 = "*"
petgraph = "*"
rayon = "*"
regex = "*"
rust-htslib = { version = "*", features = ["gcs", "serde_feature"] }
skydive = { path = "../skydive" }

[profile.release]
debug = true