[package]
name = "hidive"
version = "0.1.48"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
#arrow2 = "*"
bio = "2.0.1"
chrono = "0.4.38"
clap = { version = "4.5.1", features = ["derive"] }
env_logger = "0.11.4"
eyre = "0.6.8"
flate2 = "1.0.30"
needletail = "0.5.1"
noodles = "0.78.0"
path-absolutize = "3.1.1"
parquet = "52.1.0"
petgraph = "0.6.5"
#poasta = { path = "/Users/kiran/repositories/poasta" }
#polars = "*"
rayon = "1.10.0"
regex = "1.10.5"
rust-htslib = { version = "0.47.0", features = ["gcs", "serde_feature"] }
serde = "1.0.204"
serde_json = "1.0.120"
skydive = { path = "../skydive" }
url = "2.5.2"