[package]
name = "hidive"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
#arrow2 = "*"
bio = "*"
clap = { version = "4.5.1", features = ["derive"] }
eyre = "0.6.8"
needletail = "*"
noodles = "*"
parquet = "*"
path-absolutize = "3.1.1"
petgraph = "*"
#poasta = { path = "/Users/kiran/repositories/poasta" }
#polars = "*"
rayon = "*"
regex = "*"
rust-htslib = { version = "*", features = ["gcs", "serde_feature"] }
serde_json = "*"
skydive = { path = "../skydive" }
url = "*"

[profile.release]
debug = true
