[package]
name = "hidive"
version = "0.1.38"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
#arrow2 = "*"
bio = "*"
chrono = "*"
clap = { version = "4.5.1", features = ["derive"] }
env_logger = "*"
eyre = "0.6.8"
flate2 = "*"
needletail = "*"
noodles = "*"
path-absolutize = "3.1.1"
parquet = "*"
petgraph = "*"
#poasta = { path = "/Users/kiran/repositories/poasta" }
#polars = "*"
rayon = "*"
regex = "*"
rust-htslib = { version = "*", features = ["gcs", "serde_feature"] }
serde = "*"
serde_json = "*"
skydive = { path = "../skydive" }
url = "*"