[package]
name = "pydive"
version = "0.1.13"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pydive"
crate-type = ["cdylib"]

[dependencies]
skydive = { path = "../skydive" }
pyo3 = { version = "0.16.5", features = ["extension-module"] }
