[package]
name = "skydive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debruijn = { git = "https://github.com/10XGenomics/rust-debruijn.git" }
parquet = "*"
petgraph = "*"
polars = { version = "*", features = ["parquet", "lazy", "csv-file", "strings", "temporal", "dtype-duration", "dtype-categorical", "concat_str", "list", "list_eval", "rank", "lazy_regex"]}
color-eyre = {version = "*"}
rand = {version = "*"}
reqwest = { version = "*", features = ["blocking"]}
serde = "*"
serde_derive = "*"
serde_json = "*"
unzip-n = "*"