[package]
name = "skydive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "*"
color-eyre = {version = "*"}
# debruijn = { git = "https://github.com/10XGenomics/rust-debruijn.git" }
# kmers = { git = "https://github.com/COMBINE-lab/kmers", branch = "main" }
needletail = "*"
parquet = "*"
petgraph = "*"
polars = { version = "*", features = ["parquet", "lazy", "csv-file", "strings", "temporal", "dtype-duration", "dtype-categorical", "concat_str", "list", "list_eval", "rank", "lazy_regex"]}
rand = {version = "*"}
reqwest = { version = "*", features = ["blocking"]}
serde = "*"
serde_derive = "*"
serde_json = "*"
unzip-n = "*"