name: CI/CD
on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Write commit message
      run: git log --format=%B -n 1 ${{ github.event.after }} > release_notes.txt

    - name: Github Bumpversion Action
      id: version-bump
      uses: jasonamyers/github-bumpversion-action@v1.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true

    - name: Create Github release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version-bump.outputs.new_ver }}
        release_name: 'v${{ steps.version-bump.outputs.new_ver }}'
        body_path: "release_notes.txt"
        draft: false
        prerelease: false

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Configure Docker to use gcloud credentials
      run: gcloud auth configure-docker us.gcr.io -q

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./docker
        push: true
        tags: us.gcr.io/broad-dsp-lrma/lr-hidive:${{ steps.version-bump.outputs.new_ver }}
        build-args: |
          branch=v${{ steps.version-bump.outputs.new_ver }}
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          type=gha,scope=${{ github.workflow }}
        cache-to: |
          type=local,dest=/tmp/.buildx-cache-new,mode=max
          type=gha,mode=max,scope=${{ github.workflow }}