# Continuous integration test of any branch.

name: CI
on:
  push:
    branches-ignore:
    - main

jobs:
  # Build Docker image
  build_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Work around permissions issue
      run: git config --global --add safe.directory /__w/hidive/hidive
    - uses: 'actions/checkout@v2'

    - name: Install clang and libclang-dev
      run: sudo apt-get update && sudo apt-get install -y clang libclang-dev

    - name: Set LIBCLANG_PATH environment variable
      run: echo "LIBCLANG_PATH=/usr/lib/llvm-10/lib" >> $GITHUB_ENV

    - name: Verify libclang location
      run: ls -l /usr/lib/llvm-10/lib | grep libclang

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Image
      run: |-
        TAG=$(git rev-parse --abbrev-ref HEAD)
        cd docker
        docker build --build-arg branch=$TAG -t us.gcr.io/broad-dsp-lrma/lr-hidive:$TAG .
        gcloud auth configure-docker -q
        docker push -q us.gcr.io/broad-dsp-lrma/lr-hidive:$TAG
