name: CI
on:
  push:
    branches-ignore:
    - main

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Work around permissions issue
      run: git config --global --add safe.directory /__w/hidive/hidive
    - uses: 'actions/checkout@v3'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Configure Docker to use gcloud credentials
      run: gcloud auth configure-docker us.gcr.io -q

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./docker
        push: true
        tags: us.gcr.io/broad-dsp-lrma/lr-hidive:${{ github.ref_name }}
        build-args: |
          branch=${{ github.ref_name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache