name: Build and deploy site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build documentation
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfreetype6-dev libfontconfig1-dev
          cargo doc --no-deps

      - name: Finalize documentation
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=hidive/index.html\">" > target/doc/index.html
          touch target/doc/.nojekyll

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: target/doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Ensure this is the correct branch for GitHub Pages
          folder: target/doc
